version: '3.8'

services:
  dms_api:
    build:
      context: DocumentManagementSystem.API/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge