#version: '3.8'

services:
  dms_api:
    build:
      context: .
      dockerfile: DocumentManagementSystem/API/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__DefaultConnection=Host=dms_db;Port=5432;Username=postgres;Password=postgres;Database=dmsdb
      - RABBITMQ__HOST=dms_rabbitmq
      - RABBITMQ__QUEUE=ocr_queue
    networks:
      - app-network
    depends_on:
      - dms_db
      - dms_rabbitmq

  dms_ui:
    build:
      context: DocumentManagementSystem/UI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    networks:
      - app-network
    depends_on:
      - dms_api
  
  dms_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dmsdb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  dms_rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "9093:15672"
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  dms_ocr:
    build:
      context: .
      dockerfile: DocumentManagementSystem/OcrWorkerService/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8082
      - RabbitMQ__Host=dms_rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__QueueName=ocr_queue
    entrypoint: ["sh", "-c", "sleep 25 && dotnet OcrWorkerService.dll"]
    networks:
      - app-network
    depends_on:
      - dms_rabbitmq

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
